CREATE TABLE `data_platform_airway_header_data`
(
  `Airway`                               int(16) NOT NULL,
  `AirwayType`                           varchar(4) NOT NULL,
  `AirwayOwner`                          int(12) NOT NULL,
  `AirwayOwnerBusinessPartnerRole`       varchar(40) NOT NULL,
  `Brand`                                int(16) NOT NULL,
  `PersonResponsible`                    varchar(40) DEFAULT NULL,
  `URL`                                  varchar(200) DEFAULT NULL,
  `ValidityStartDate`                    date NOT NULL,
  `ValidityEndDate`                      date NOT NULL,
  `DepartureAirport`                     int(16) NOT NULL,
  `DestinationAirport`                   int(16) NOT NULL,
  `Description`                          varchar(60) NOT NULL,
  `LongText`                             varchar(1000) NOT NULL,
  `Introduction`                         varchar(200) DEFAULT NULL,
  `Project`                              int(16) DEFAULT NULL,
  `WBSElement`                           int(8) DEFAULT NULL,
  `Tag1`                                 varchar(40) DEFAULT NULL,
  `Tag2`                                 varchar(40) DEFAULT NULL,
  `Tag3`                                 varchar(40) DEFAULT NULL,
  `Tag4`                                 varchar(40) DEFAULT NULL,
  `CreationDate`                         date NOT NULL,
  `CreationTime`                         time NOT NULL,
  `LastChangeDate`                       date NOT NULL,
  `LastChangeTime`                       time NOT NULL,
  `CreateUser`                           int(12) NOT NULL,
  `LastChangeUser`                       int(12) NOT NULL,
  `IsReleased`                           tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`                  tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Airway`),

    CONSTRAINT `DPFMAirwayHeaderDataAirwayType_fk` FOREIGN KEY (`AirwayType`) REFERENCES `data_platform_airway_type_airway_type_data` (`AirwayType`),
    CONSTRAINT `DPFMAirwayHeaderDataAirwayOwner_fk` FOREIGN KEY (`AirwayOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMAirwayHeaderDataAirwayOwnerBPRole_fk` FOREIGN KEY (`AirwayOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMAirwayHeaderDataBrand_fk` FOREIGN KEY (`Brand`) REFERENCES `data_platform_brand_header_data` (`Brand`),
    CONSTRAINT `DPFMAirwayHeaderDataDptAirport_fk` FOREIGN KEY (`DepartureAirport`) REFERENCES `data_platform_airport_header_data` (`Airport`),
    CONSTRAINT `DPFMAirwayHeaderDataDstAirport_fk` FOREIGN KEY (`DestinationAirport`) REFERENCES `data_platform_airport_header_data` (`Airport`),
    CONSTRAINT `DPFMAirwayHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMAirwayHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMAirwayHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMAirwayHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
